=== AlienSmith/The-Space-between-Us/Altova/MapForce2018/MapForceExamples/Tutorial/Addresses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2017 sp2 (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">	
	<xs:element name="Addresses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Address" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Address">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FirstName"/>
				<xs:element ref="LastName"/>
				<xs:element ref="City"/>
				<xs:element ref="Street"/>
				<xs:element ref="Number"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="FirstName" type="xs:string"/>
	<xs:element name="LastName" type="xs:string"/>
	<xs:element name="City" type="xs:string"/>
	<xs:element name="Number" type="xs:string"/>
	<xs:element name="Street" type="xs:string"/>	
</xs:schema>

=== AlienSmith/The-Space-between-Us/Altova/MapForce2018/MapForceExamples/Tutorial/Addresses.xml
<?xml version="1.0" encoding="UTF-8"?>
<Addresses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Addresses.xsd">
	<Address>
		<FirstName>Marquita</FirstName>
		<LastName>Bailey</LastName>
		<City>Bridgedell</City>
		<Street>Olive Street</Street>
		<Number>4</Number>
	</Address>
	<Address>
		<FirstName>Totie</FirstName>
		<LastName>Rea</LastName>
		<City>Roseford</City>
		<Street>Evergreen Lane</Street>
		<Number>34</Number>
	</Address>
	<Address>
		<FirstName>Mark</FirstName>
		<LastName>Marzolla</LastName>
		<City>Elfville</City>
		<Street>Creek Road</Street>
		<Number>3</Number>
	</Address>
</Addresses>
