=== AlienSmith/The-Space-between-Us/Altova/MapForce2018/MapForceExamples/Tutorial/books.xsd
<!-- edited with XMLSpy v2015 rel. 3 (http://www.altova.com) by Mr. Nobody (Altova GmbH) -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
	<xsd:element name="books">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="book" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="book" type="bookType"/>
	<xsd:complexType name="bookType">
		<xsd:sequence>
			<xsd:element name="author" type="xsd:string"/>
			<xsd:element name="title" type="xsd:string"/>
			<xsd:element name="category" type="xsd:string"/>
			<xsd:element name="year" type="xsd:string"/>
		</xsd:sequence>
		<xsd:attribute name="id" type="xsd:string"/>
	</xsd:complexType>
</xsd:schema>

=== AlienSmith/The-Space-between-Us/Altova/MapForce2018/MapForceExamples/Tutorial/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd">
	<book id="1">
		<author>Mark Twain</author>
		<title>The Adventures of Tom Sawyer</title>
		<category>Fiction</category>
		<year>1876</year>
	</book>
	<book id="2">
		<author>Franz Kafka</author>
		<title>The Metamorphosis</title>
		<category>Fiction</category>
		<year>1912</year>
	</book>
	<book id="3">
		<author>Herman Melville</author>
		<title>Moby Dick</title>
		<category>Fiction</category>
		<year>1851</year>
	</book>
	<book id="4">
		<author>Miguel de Cervantes</author>
		<title>Don Quixote</title>
		<category>Fiction</category>
		<year>1605</year>
	</book>
</books>
