=== AlienSmith/The-Space-between-Us/Altova/MapForce2018/MapForceExamples/Tutorial/library.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
	<xsd:element name="library">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="last_updated" type="xsd:dateTime"/>
				<xsd:element name="publication" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="id" type="xsd:string"/>
							<xsd:element name="author" type="xsd:string"/>
							<xsd:element name="title" type="xsd:string"/>
							<xsd:element name="genre" type="xsd:string"/>
							<xsd:element name="publish_year" type="xsd:integer"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== AlienSmith/The-Space-between-Us/Altova/MapForce2018/MapForceExamples/Tutorial/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="library.xsd">
	<last_updated>2015-03-09T12:17:31+01:00</last_updated>
	<publication>
		<id>5</id>
		<author>Alexandre Dumas</author>
		<title>The Three Musketeers</title>
		<genre>Fiction</genre>
		<publish_year>1844</publish_year>
	</publication>
	<publication>
		<id>6</id>
		<author>Jules Verne</author>
		<title>Around the World in Eighty Days</title>
		<genre>Fiction</genre>
		<publish_year>1873</publish_year>
	</publication>
	<publication>
		<id>7</id>
		<author>Edgar Allan Poe</author>
		<title>The Murders in the Rue Morgue</title>
		<genre>Fiction</genre>
		<publish_year>1841</publish_year>
	</publication>
</library>
