=== AlienSmith/The-Space-between-Us/Altova/MapForce2018/MapForceExamples/Tutorial/MissingFields.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Articles">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Article" type="ArticleType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ArticleType">
		<xs:sequence>
			<xs:element name="Number" type="xs:integer" minOccurs="0"/>
			<xs:element name="Name" type="xs:string" minOccurs="0"/>
			<xs:element name="SinglePrice" type="xs:decimal" minOccurs="0"/>
			<xs:element name="Description" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== AlienSmith/The-Space-between-Us/Altova/MapForce2018/MapForceExamples/Tutorial/MissingFields.xml
<?xml version="1.0" encoding="UTF-8"?>
<Articles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MissingFields.xsd">
	<Article>		
		<Name>T-Shirt</Name>
		<SinglePrice>25</SinglePrice>
		<Description>Available in all sizes</Description>
	</Article>
	<Article>
		<Number>2</Number>		
		<SinglePrice>2.30</SinglePrice>
	</Article>
	<Article>
		<Number>3</Number>
		<Name>Pants</Name>
		<Description>Limited stock</Description>
	</Article>
	<Article>
		<Number>4</Number>
		<Name>Jacket</Name>
		<SinglePrice>57.50</SinglePrice>
	</Article>
</Articles>
