=== AlienSmith/The-Space-between-Us/Altova/MapForce2018/MapForceExamples/Tutorial/People.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2017 sp2 (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Email" type="xs:string"/>
	<xs:element name="Phone" type="xs:int"/>
	<xs:element name="People">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Person" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Person">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FirstName"/>
				<xs:element ref="LastName"/>
				<xs:element ref="Email"/>
				<xs:element ref="Phone"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="LastName" type="xs:string"/>
	<xs:element name="FirstName" type="xs:string"/>
</xs:schema>

=== AlienSmith/The-Space-between-Us/Altova/MapForce2018/MapForceExamples/Tutorial/People.xml
<?xml version="1.0" encoding="UTF-8"?>
<People xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="People.xsd">
	<Person>
		<FirstName>Marquita</FirstName>
		<LastName>Bailey</LastName>
		<Email>m.bailey@nanonull.com</Email>
		<Phone>555323698</Phone>
	</Person>
	<Person>
		<FirstName>Totie</FirstName>
		<LastName>Rea</LastName>
		<Email>t.rea@nanonull.com</Email>
		<Phone>555598653</Phone>
	</Person>
	<Person>
		<FirstName>Mark</FirstName>
		<LastName>Marzolla</LastName>
		<Email>m.marzolla@nanonull.com</Email>
		<Phone>555000876</Phone>
	</Person>
	<Person>
		<FirstName>Laurianne</FirstName>
		<LastName>Huisman</LastName>
		<Email>l.huisman@nanonull.com</Email>
		<Phone>555357688</Phone>
	</Person>
</People>
