=== AlienSmith/The-Space-between-Us/Altova/MapForce2018/MapForceExamples/Tutorial/Products.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
	<xsd:element name="products">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="product" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="product" type="productType"/>
	<xsd:complexType name="productType">
		<xsd:sequence>
			<xsd:element name="id" type="xsd:string"/>
			<xsd:element name="color" type="xsd:string"/>
			<xsd:element name="size" type="xsd:string"/>			
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== AlienSmith/The-Space-between-Us/Altova/MapForce2018/MapForceExamples/Tutorial/Products.xml
<?xml version="1.0" encoding="UTF-8"?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd">
	<product>
		<id>1</id>
		<color>red</color>
		<size>10</size>		
	</product>
	<product>
		<id>2</id>
		<color>blue</color>
		<size>20</size>		
	</product>
	<product>
		<id>3</id>
		<color>green</color>
		<size>30</size>		
	</product>
</products>
